name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  html: ^0.15.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.1
  provider: ^6.1.2
  flutter_tts: ^4.0.2 # Added flutter_tts dependency
  flutter_sound: ^9.2.13 # New import for audio recording
  permission_handler: ^11.3.1 # New import for permissions
  speech_to_text: ^6.6.1 # New import for local ASR on mobile

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.14
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
